version: '3.8'

services:
  postgres:
    image: ghcr.io/cloudnative-pg/postgresql
    container_name: bookcatalog_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookcatalog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
